{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: {{ include "mesh-lab.fullname" . }}
  labels:
    {{- include "mesh-lab.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mesh-lab.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.rollout.enabled }}
  strategy:
    {{- if eq .Values.rollout.strategy "blueGreen" }}
    blueGreen:
      activeService: {{ include "mesh-lab.fullname" . }}
      previewService: {{ include "mesh-lab.fullname" . }}-preview
      autoPromotionEnabled: {{ .Values.rollout.blueGreen.autoPromotionEnabled }}
      scaleDownDelaySeconds: {{ .Values.rollout.blueGreen.scaleDownDelaySeconds }}
      postPromotionAnalysis:
        templates:
          - templateName: {{ include "mesh-lab.fullname" . }}-success-rate
        args:
          - name: rollouts-pod-template-hash
            valueFrom:
              podTemplateHashValue: Latest
    {{- else }}
    canary:
      maxSurge: {{ .Values.rollout.canary.maxSurge }}
      {{- if .Values.rollout.canary.trafficRouting.enabled }}
      stableService: {{ include "mesh-lab.fullname" . }}
      canaryService: {{ include "mesh-lab.fullname" . }}-canary
      trafficRouting:
        istio:
          virtualService:
            name: {{ include "mesh-lab.fullname" . }}-vsvc
            routes:
              - primary
      {{- end }}
      steps:
        {{- range .Values.rollout.canary.steps }}
        {{- if hasKey . "setWeight" }}
        - setWeight: {{ .setWeight }}
        {{- else if hasKey . "pause" }}
        - pause:
            duration: {{ .pause.duration }}
        {{- else if hasKey . "analysis" }}
        - analysis:
            templates:
              - templateName: {{ include "mesh-lab.fullname" $ }}-success-rate
            args:
              - name: rollouts-pod-template-hash
                valueFrom:
                  podTemplateHashValue: Latest
        {{- end }}
        {{- end }}
    {{- end }}
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mesh-lab.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Values.app.version | quote }}
    spec:
      serviceAccountName: {{ include "mesh-lab.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 35
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: mesh-lab
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: APP_NAME
              value: {{ .Values.app.name | quote }}
            - name: APP_VERSION
              value: {{ .Values.app.version | quote }}
            - name: CHAOS_ERROR_RATE
              value: {{ .Values.chaos.errorRate | quote }}
            {{- range .Values.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
