{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mesh-lab-inventory.serviceAccountName" . }}
  labels:
    {{- include "mesh-lab-inventory.labels" . | nindent 4 }}
{{- end }}
