apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mesh-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/himanshugvu/deployment.git
    targetRevision: main
    path: deploy/istio/config
    directory:
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: mesh-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
