apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mesh-lab
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/himanshugvu/deployment.git
    targetRevision: main
    path: deploy/helm/mesh-lab
    helm:
      releaseName: mesh-lab
      parameters:
        - name: rollout.enabled
          value: "true"
        - name: rollout.strategy
          value: canary
        - name: monitoring.serviceMonitor.enabled
          value: "true"
        - name: monitoring.serviceMonitor.additionalLabels.release
          value: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: mesh-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
